config/routes.rb
Rails.application.routes.draw do

  get '/' => 'contacts#dashboard'

  resources :users
    resources :contacts do
      collection do
        get 'search'
      end
    end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="page-footer" id="footer">
    <div class="container">
      <div class="row">
        <div class="footer-copyright">
          <div class="container">
          © 2014 Copyright Text
        <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>

app/views/layouts/_importFiles.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<!-- METISMENU SCRIPTS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/metisMenu/2.5.2/metisMenu.js"></script>
<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
<!-- CUSTOM SCRIPTS -->

app/views/layouts/_navigation.html.erb
<nav>
  <div class="nav-wrapper blue darken-1">
    <a href="#" class="brand-logo" id="a_tag" >QBase</a>
    <ul class="right hide-on-med-and-down">
      <li class="searchBtn" ><a href="#"><i class="glyphicon glyphicon-search left"></i></a></li>
      <li><%= link_to '' %><i class="glyphicon glyphicon-user right"></i></a></li>
      <% if current_user %>
      <li>
        <!--Check if current user if logged in-->
        <%#= link_to 'My Profile', user_path(@user), method: :get %>
        </li>
          <li><%= link_to 'Contacts', contacts_path, method: :get, class: 'sessionCtrlr', id: 'a_tag' %></li>
      <% else %>

        <li><%= link_to 'Dashboard', contacts_path, id: 'a_tag', class: 'sessionCtrlr' %></li>
        <li><%= link_to '',  id: 'a_tag' %></li>

      <% end %>


    </ul>
  </div>
</nav>

<!-- End of Navigation Bar -->

app/views/layouts/_onlineChat.html.erb
<% if current_user %>
    <span class="user-info blue lighten-3">
      <div class="profile-pic">
        <img src="https://cdn1.iconfinder.com/data/icons/user-pictures/100/male3-512.png" alt="My Image" width="50" height="50" />
      </div>
      <p class="col-md-12 blue lighten-5 online_user right">
        Online:  <%= current_user.email[/[^@]+/] %>
        <%= current_user.email %>
      </p>
    </span>
<% end %>

app/views/layouts/_search.html.erb
<input type="text" name="search" hidden placeholder="Search..">

app/views/layouts/_sideBar.html.erb
<div id="side-bar">
    <div class="list-group" style="text-align: right;">
      <a class="list-group-item" href="/">&nbsp; <i class="glyphicon glyphicon-home" aria-hidden="true"></i></a>
      <a class="list-group-item" href="/contacts">&nbsp; <i class="glyphicon glyphicon-user" aria-hidden="true"></i></a>
      <a class="list-group-item" href="#">&nbsp; <i class="glyphicon glyphicon-paperclip" aria-hidden="true"></i></a>
      <a class="list-group-item" href="#">&nbsp; <i class="glyphicon glyphicon-search" aria-hidden="true"></i></a>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- BOOTSTRAP STYLES-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- FONTAWESOME ICONS STYLES-->
    <link rel="stylesheet" href="https://path/to/font-awesome/css/font-awesome.min.css">    <!--CUSTOM STYLES-->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>

  </head>

  <body>
    <!-- navigation tag partial rendered -->
    <%= render partial: 'layouts/navigation' %>

    <!-- search bar partial hidden -->

    <!-- Side bar nav -->
    <%= render partial: 'layouts/sideBar' %>
    <!-- Yield a block of code -->
    <%= yield %>

    <%= render partial: 'layouts/onlineChat' %>

    <%= render partial: 'layouts/importFiles' %>

    <!-- footer of the page -->
    <%#= render partial: 'layouts/footer' %>
  </body>
</html>